<x-admin-layout>
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Kit Code Details') }}
            </h2>
            <div class="flex space-x-3">
                <a href="{{ route('admin.kit-codes.edit', $kitCode) }}" 
                   class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    ✏️ Edit
                </a>
                <a href="{{ route('admin.kit-codes.index') }}" 
                   class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                    ← Back to List
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <!-- Kit Code Card -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg mb-6">
                <div class="p-6">
                    <div class="flex items-center justify-between mb-6">
                        <div class="flex items-center">
                            <div class="w-16 h-16 bg-gradient-to-br from-purple-500 to-pink-600 rounded-full flex items-center justify-center mr-4">
                                <span class="text-white font-bold text-2xl">K</span>
                            </div>
                            <div>
                                <h1 class="text-3xl font-bold text-gray-900 font-mono">{{ $kitCode->code }}</h1>
                                <p class="text-lg text-gray-600">{{ $kitCode->module->module_name ?? 'No Module' }}</p>
                            </div>
                        </div>
                        <div>
                            @if($kitCode->status === 'unused')
                                <span class="inline-flex items-center px-4 py-2 rounded-full text-lg font-medium bg-green-100 text-green-800">
                                    ✅ Available
                                </span>
                            @elseif($kitCode->status === 'used')
                                <span class="inline-flex items-center px-4 py-2 rounded-full text-lg font-medium bg-orange-100 text-orange-800">
                                    👤 Used
                                </span>
                            @else
                                <span class="inline-flex items-center px-4 py-2 rounded-full text-lg font-medium bg-red-100 text-red-800">
                                    🚫 Blocked
                                </span>
                            @endif
                        </div>
                    </div>

                    <!-- Details Grid -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <!-- Module Information -->
                        <div class="bg-gray-50 p-4 rounded-lg">
                            <h3 class="text-lg font-medium text-gray-900 mb-3">📚 Module Information</h3>
                            <div class="space-y-2">
                                <div>
                                    <span class="text-sm font-medium text-gray-500">Module Name:</span>
                                    <p class="text-sm text-gray-900">{{ $kitCode->module->module_name ?? 'Not assigned' }}</p>
                                </div>
                                @if($kitCode->module)
                                    <div>
                                        <span class="text-sm font-medium text-gray-500">Focus Area:</span>
                                        <p class="text-sm text-gray-900">{{ $kitCode->module->focus_area }}</p>
                                    </div>
                                    <div>
                                        <span class="text-sm font-medium text-gray-500">Age Group:</span>
                                        <p class="text-sm text-gray-900">{{ $kitCode->module->suggested_age_group }}</p>
                                    </div>
                                @endif
                            </div>
                        </div>

                        <!-- Generation Information -->
                        <div class="bg-gray-50 p-4 rounded-lg">
                            <h3 class="text-lg font-medium text-gray-900 mb-3">⚙️ Generation Information</h3>
                            <div class="space-y-2">
                                <div>
                                    <span class="text-sm font-medium text-gray-500">Generated By:</span>
                                    <p class="text-sm text-gray-900">{{ $kitCode->generatedBy->name ?? 'Unknown' }}</p>
                                </div>
                                <div>
                                    <span class="text-sm font-medium text-gray-500">Generated At:</span>
                                    <p class="text-sm text-gray-900">{{ $kitCode->created_at->format('F d, Y \a\t H:i') }}</p>
                                </div>
                                <div>
                                    <span class="text-sm font-medium text-gray-500">Code Status:</span>
                                    <p class="text-sm text-gray-900 capitalize">{{ $kitCode->status }}</p>
                                </div>
                            </div>
                        </div>

                        <!-- Usage Information -->
                        @if($kitCode->status === 'used')
                            <div class="bg-blue-50 p-4 rounded-lg md:col-span-2">
                                <h3 class="text-lg font-medium text-gray-900 mb-3">👤 Usage Information</h3>
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div>
                                        <span class="text-sm font-medium text-gray-500">Used By:</span>
                                        <p class="text-sm text-gray-900">{{ $kitCode->usedBy->name ?? 'Unknown User' }}</p>
                                    </div>
                                    <div>
                                        <span class="text-sm font-medium text-gray-500">Used At:</span>
                                        <p class="text-sm text-gray-900">{{ $kitCode->used_at ? $kitCode->used_at->format('F d, Y \a\t H:i') : 'Unknown' }}</p>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <!-- Actions Card -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-medium text-gray-900 mb-4">🔧 Actions</h3>
                    <div class="flex flex-wrap gap-3">
                        <a href="{{ route('admin.kit-codes.edit', $kitCode) }}" 
                           class="inline-flex items-center px-4 py-2 bg-blue-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-blue-700 focus:bg-blue-700 active:bg-blue-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150">
                            ✏️ Edit Code
                        </a>
                        
                        @if($kitCode->status === 'unused')
                            <form method="POST" action="{{ route('admin.kit-codes.update', $kitCode) }}" class="inline">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="blocked">
                                <input type="hidden" name="module_id" value="{{ $kitCode->module_id }}">
                                <button type="submit" 
                                        class="inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 focus:bg-red-700 active:bg-red-900 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition ease-in-out duration-150"
                                        onclick="return confirm('Are you sure you want to block this code?')">
                                    🚫 Block Code
                                </button>
                            </form>
                        @endif

                        <form method="POST" action="{{ route('admin.kit-codes.destroy', $kitCode) }}" class="inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" 
                                    class="inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 focus:bg-red-700 active:bg-red-900 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition ease-in-out duration-150"
                                    onclick="return confirm('Are you sure you want to delete this kit code? This action cannot be undone.')">
                                🗑️ Delete Code
                            </button>
                        </form>

                        <a href="{{ route('admin.modules.show', $kitCode->module) }}" 
                           class="inline-flex items-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-700 focus:bg-green-700 active:bg-green-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 transition ease-in-out duration-150">
                            📚 View Module
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-admin-layout>
